### model
model_name_or_path: ./Qwen3-8B # 

### method
stage: sft
do_train: true
finetuning_type: full

### ddp
ddp_timeout: 180000000
deepspeed: ./config/ds_z2_config.json 

### dataset
dataset: dsmerge
template: qwen3
cutoff_len: 16384 # 2048 # 4096 # 1024
overwrite_cache: true
cache_dir: /tmp/tokenized
preprocessing_num_workers: 16

### output
output_dir: /tmp/qwen3_8b_p8 
logging_steps: 1
#save_steps: 1000
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2 # 32B: 显存不够 # 16 # 7B: 8
gradient_accumulation_steps: 2 # 2
learning_rate: 5.0e-6 # 1.0e-5
num_train_epochs: 3 # 2
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
gradient_checkpointing: true
#resume_from_checkpoint: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: "no"
eval_steps: 10000
